#' Read in Hayes data from SPSS or R output
#' 
#' @description Wrapper for the `read_hayes_plot_data_spss` and 
#' `read_hayes_plot_data_R` functions that automatically detects
#' the correct function to call.
#' 
#' @param hayes_data The data object from which to extract the information. Can be 
#' a .txt file (exported from SPSS via copy/paste) or an R object, generated by process
#' for R. 
#' 
#' @returns A list of class HayesData consisting of the plot_data for visualizing the interaction as well as the various significance 
#' measures from the Hayes SPSS output as well as the model description.

read_hayes_plot_data <- function(hayes_data){
  
}